### ISSUE TITLE
I would like to add the titles for the URLs for not confounding the URLs

### ISSUE THREAD

**Issue by gusbemacbe** [marioestrada/safari-omnikey#10]
Hello,

I added many search sites, but they have similar URLs, only that the search of the same site are different. I suggest you add a functionality of adding the titles for not confounding the URLs. Check my image:

![Image of Omnikey](http://i.imgur.com/klf5DpT.png)

These are the same URLs, but they're different, for example: 
- bablaafr ➜ Babla.fr ➜ Babla English-French;
- bablafra ➜ Babla.fr ➜ Babla French-English;
  etc.

**Comment by marioestrada** [comment]
Will take this into consideration for next release :)

**Comment by gusbemacbr** [comment]
You didn't add the feature. :'(

I would like to order alphabetically the keys.
