### ISSUE TITLE
Change what a space in the query gets converted to

### ISSUE THREAD

**Issue by rltbennett** [marioestrada/safari-omnikey#11]
As is, spaces in queries get converted to plus signs (%2B). However it would useful if the extension could be configured to convert spaces to another character, in particular %20, a literal space character. For instance, on Wikipedia, http://en.wikipedia.org/wiki/Barack%2BObama links to a nonexistent article "Barack+Obama", while http://en.wikipedia.org/wiki/Barack%20Obama links to the correct article. Thus this extension does not allow you type e.g. "wiki Barack Obama"; you must type "wiki Barack_Obama".

Perhaps the value could be set on a per-key basis but for now I would be happy with a global change.

**Comment by marioestrada** [comment]
This is undocumented but you can set `{%search}` instead of `{search}` for alternative encoding of spaces.
