### ISSUE TITLE
Import/Export button doesn't do anything

### ISSUE THREAD

**Issue by swrobel** [marioestrada/safari-omnikey#14]
Am I missing something? Extension version 1.4 on Safari 9.1

![screencast](http://g.recordit.co/uPdfjD1KTQ.gif)

**Comment by willxy** [comment]
Hmm, I don't experience the import/export/add-site buttons that seem to appear under the popup menu, in your capture above.  When I click on import/export in the popup menu, it changes the popup menu to show an area to copy current data (export), and an area to paste in new data (import).  I have extension version 1.40 and Safari 9.1.2

![screen shot 2016-08-16 at 2 44 23 pm](https://cloud.githubusercontent.com/assets/18635433/17713368/241474c4-63c0-11e6-9238-f4007f89be3d.png)

![screen shot 2016-08-16 at 2 44 41 pm](https://cloud.githubusercontent.com/assets/18635433/17713373/2bcbb2ae-63c0-11e6-9f33-b5a7cf1020ae.png)

**Comment by swrobel** [comment]
Thanks for checking. I just tried again and it works fine for me. Not sure what the issue is.
