### ISSUE TITLE
In OSX Sierra, editing of sites is disabled

### ISSUE THREAD

**Issue by andrewCMU** [marioestrada/safari-omnikey#16]
See Screenshot, in OSX Sierra you can no longer add/edit sites. It should be mentioned that all previous sites added still function.

<img width="482" alt="screen shot 2016-11-16 at 12 14 20 pm" src="https://cloud.githubusercontent.com/assets/3411672/20357588/8f1cb15e-abf6-11e6-9d79-ad893a1655b6.png">

**Comment by marioestrada** [comment]
I haven't had time to look into this, I'll try to prioritize this since I'm also a heavy user of the extension

**Comment by marioestrada** [comment]
I think this might have been an issue with parsing some of the sites that should be resolved by now.

**Comment by andrewCMU** [comment]
Correct, this is now fixed.

Thanks!
