### ISSUE TITLE
Forward-slash gets url-encoded and breaks search query

### ISSUE THREAD

**Issue by EricCrosson** [marioestrada/safari-omnikey#17]
Hello,

Great project! It's really helping me feel at home in macOS. 

I am trying to replicate a use-case of the Chrome search-engines where I use the 'Key' as an alias and use the '{ search }' as the last half of the url.  For a contrived example, consider

Property | Value
---|---
Key | g
URL | private.gitlab.instance.com
{ search } | marioestrada/safari-omnikey

When '{ search }' does not contain the '/' character, it works like a charm! But safari is encoding the '/' into '%2F' and throws a 'Page not found' error. 

This may not be a bug in your project, and if a solution exists it may be the case that the fix should be applied elsewhere.  Having said that, the procedure for disabling this auto-encoding of urls would make a welcome contribution to this project's documentation.

Thanks again for the extension,

Happy hacking!

**Comment by marioestrada** [comment]
yeah this is how url encoding is supposed to work looks like this might be an issue with how gitlab handles query parameters
