### ISSUE TITLE
Does not work with startpage as default search engine

### ISSUE THREAD

**Issue by ylluminarious** [marioestrada/safari-omnikey#18]
I have [startpage.com](https://www.startpage.com) set as my default search engine via their [Safari extension](https://www.startpage.com/extensions/safari/StartPage-HTTPS.safariextz). Unfortunately, it seems that said extension and omnikey conflict with each other because whenever I have the startpage extension on, I cannot use omnikey since my search text is directed to startpage instead of the website that I specify via omnikey.

**Comment by marioestrada** [comment]
you can set the default search engine via Omnikey too without the need for both extensions, there's an option at the bottom of the settings popup that let's you choose a default search engine from your saved sites. Add this as the URL: `https://www.startpage.com/do/search?query={search}`

**Comment by ylluminarious** [comment]
@marioestrada Thanks, that does the trick.
