### ISSUE TITLE
Changing the keyword to an exclamation point breaks everything.

### ISSUE THREAD

**Issue by bensherman** [marioestrada/safari-omnikey#2]
I added a keyword to force an http:// to not use any search.  Unknown to me, ! is a reserved keyword.  This appears to have made my keywords disappear. 

Example:

Keyword: !
Url: http://{search}

**Comment by joshenders** [comment]
Can you submit a screenshot of your current sites with key + url?

**Comment by bensherman** [comment]
After they went away, I stopped using the plugin. I was more than a year ago, sorry.

**Comment by marioestrada** [comment]
ugg yeah `!` is used internally, sad this was an issue for you :(
