### ISSUE TITLE
Keywords are not working

### ISSUE THREAD

**Issue by fabiantheblind** [marioestrada/safari-omnikey#4]
Hi there, your extension is great. Thanks a lot. My problem is I tried to add some searches with different keywords but only the default is working.  
The strangest thing is on my other computer it works. How can I debug or fix this?

**Comment by marioestrada** [comment]
Are you still having this issue?

**Comment by fabiantheblind** [comment]
Hi @marioestrada I moved away from safari and started using chrome. :smile:

**Comment by shreyas** [comment]
doesn't work for me. only one default keyword worked so far (imdb); rest of them run as searches in google. i renamed amazon and youtube keywords after installation. no other changes to defaults anywhere. 

installed sometime back from github location. 

mac os x el capitan 10.11.6 (15G1004) on macbook air
safari version: Version 10.0 (11602.1.50.0.10)
