### ISSUE TITLE
How do you import?

### ISSUE THREAD

**Issue by mtrang** [marioestrada/safari-omnikey#6]
How do you import the data that has been saved? When I paste it, it doesn't import.

**Comment by fletom** [comment]
yep, import doesn't work.

**Comment by svens** [comment]
As a workaround, you can maintain omnikey on main machine tedious manual way and then copy it's settings to other machines.
Settings file can be found with ```find . -iname '*omnikey*localstorage'```

**Comment by fletom** [comment]
@svens Nice find. That command will take a long time to run though, searching the entire current directory. A faster way to do it is only look in `~/Library/Safari/LocalStorage/`. Here's the command: `find ~/Library/Safari/LocalStorage/ -iname '*omnikey*localstorage'`

Note that these seem to be SQLite version 3 files, so you can read/edit them with an SQLite browser.

**Comment by marioestrada** [comment]
this was recently fixed with 1.3.1, sorry for the delay :)
