### ISSUE TITLE
! breaks search

### ISSUE THREAD

**Issue by jonathanlang** [marioestrada/safari-omnikey#7]
DuckDuckGo (my default search engine) has the feature of Hashbangs, which are keywords preceded by an !, so !gi takes me to Google Images for example.
Unfortunately, when I try to enter a hashbang at the beginning of my search query, it takes me to Google, which is neither my default browser search nor my default OmniKey search.

**Comment by marioestrada** [comment]
This is a limitation of the current design, I'll look into ways to improve this, open to suggestions :)

**Comment by marioestrada** [comment]
Should be working with `1.4.0`, it adds an option for disabling `!` force search
